public class Data {
    private static final String[][] WORDS1 = {{"(V1 Infinitive)", "(V2 Past Simple)", "(V3 Participle)", "(Ukrainian)"},
            {"be", "was were", "been", "бути"},
            {"become", "became", "become", "ставати"},
            {"begin", "began", "begun", "починати"},
            {"break", "broke", "broken", "ламати"},
            {"bring", "brought", "brought", "приносити"},
            {"buy", "bought", "bought", "купувати"},
            {"build", "built", "built", "будувати"},
            {"catch", "caught", "caught", "ловити"},
            {"choose", "chose", "chosen", "обирати"},
            {"come", "came", "come", "приходити"},
            {"cut", "cut", "cut", "різати"},
            {"do", "did", "done", "робити"},
            {"dig", "dug", "dug", "копати"},
            {"grow", "grew", "grown", "рости"},
            {"hold", "held", "held", "тримати"},
            {"hide", "hid", "hidden", "ховати"},
            {"eat", "ate", "eaten", "їсти"},
            {"find", "found", "found", "знайти"},
            {"get", "got", "got", "отримувати"},
            {"give", "gave", "given", "давати"},
            {"go", "went", "gone", "іти"},
            {"have", "had", "had", "мати"},
            {"hear", "heard", "heard", "чути"},
            {"keep", "kept", "kept", "утримувати"},
            {"leave", "left", "left", "залишати"},
            {"lose", "lost", "lost", "втрачати"},
            {"make", "made", "made", "виготовити"},
            {"meet", "met", "met", "зустріти"},
            {"mean", "meant", "meant", "означати"},
            {"put", "put", "put", "покласти"},
            {"read", "read", "read", "читати"},
            {"run", "ran", "run", "бігти"},
            {"say", "said", "said", "казати"},
            {"see", "saw", "seen", "бачити"},
            {"sell", "sold", "sold", "продавати"},
            {"sing", "sang", "sung", "співати"},
            {"stand", "stood", "stood", "стояти"},
            {"speak", "spoke", "spoken", "говорити"},
            {"sit", "sat", "sat", "сидіти"},
            {"take", "took", "taken", "брати"},
            {"teach", "taught", "taught", "вчити"},
            {"tell", "told", "told", "розповідати"},
            {"win", "won", "won", "перемагати"},
            {"write", "wrote", "written", "писати"},
            {"flee", "fled", "fled", "втікати"},
            {"show", "showed", "shown", "показувати"},
            {"shut", "shut", "shut", "закрити"},
            {"hang", "hung", "hung", "повісити"},
            {"swear", "swore", "sworn", "присягатися"},
            {"swim", "swam", "swum", "плавати"}
    };
    private static final String[][] WORDS2 = {{"(V1 Infinitive)", "(V2 Past Simple)", "(V3 Participle)", "(Ukrainian)"},
            {"beat", "beat", "beaten", "бити"},
            {"bend", "bent", "bent", "згинати"},
            {"bet", "bet", "bet", "закладатися"},
            {"bite", "bit", "bitten", "вкусити"},
            {"blow", "blew", "blown", "дмухати"},
            {"cast", "cast", "cast", "відливати"},
            {"chide", "chid chode", "chid chidden", "докоряти"},
            {"cost", "cost", "cost", "коштувати"},
            {"lie", "lied", "lied", "обманювати"},
            {"deal", "dealt", "dealt", "мати справу,домовлятися"},
            {"draw", "drew", "drawn", "малювати"},
            {"dream", "dreamt, dreamed", "dreamt, dreamed", "мріяти"},
            {"drink", "drank", "drunk", "пити"},
            {"drive", "drove", "driven", "кермувати"},
            {"fall", "fell", "fallen", "падати"},
            {"fly", "flew", "flown", "літати"},
            {"forget", "forgot", "forgotten", "забувати"},
            {"forgive", "forgave", "forgiven", "пробачати"},
            {"freeze", "froze", "frozen", "заморожувати"},
            {"clothe", "clad clothed", "clad clothed", "одягати"},
            {"dive", "dived", "dived  dove", "пірнати"},
            {"hit", "hit", "hit", "влучати"},
            {"hold", "held", "held", "тримати"},
            {"know", "knew", "known", "знати"},
            {"lay", "laid", "laid", "лежати"},
            {"lead", "led", "led", "вести за собою"},
            {"learn", "learnt learned", "learnt learned", "вчити"},
            {"pay", "paid", "paid", "платити"},
            {"ring", "rang", "rung", "дзвонити (у дзвоник)"},
            {"rise", "rose", "risen", "підніматися"},
            {"send", "sent", "sent", "відсилати"},
            {"set", "set", "set", "налаштовувати"},
            {"shake", "shook", "shaken", "трусити"},
            {"shed", "shed", "shed", "линяти"},
            {"shine", "shone", "shone", "сяяти"},
            {"shoot", "shot", "shot", "стріляти"},
            {"burn", "burnt, burned", "burnt burned", "горіти"},
            {"lie", "lay", "lain", "лягти"},
            {"smell", "smelt", "smelt", "пахнути"},
            {"swing", "swung", "swung", "гойдатися"},
            {"spend", "spent", "spent", "витрачати"},
            {"feed", "fed", "fed", "годувати"},
            {"think", "thought", "thought", "думати"},
            {"understand", "understood", "understood", "розуміти"},
            {"wake", "woke", "woken", "розбудити"},
            {"leap", "leapt leaped", "leapt leaped", "стрибати"},
            {"lean", "leant leaned", "leant leaned", "спиратися"},
            {"wear", "wore", "worn", "одягати"},
            {"overcome", "overcame", "overcome", "подолати"},
            {"stick", "stuck", "stuck", "дотримуватися"},
    };
    private static final String[][] WORDS3 = {{"(V1 Infinitive)", "(V2 Past Simple)", "(V3 Participle)", "(Ukrainian)"},
            {"awake", "awoke", "awoken", "прокидатися"},
            {"bear", "bore", "born(e)", "народжуватися"},
            {"arise", "arose", "arisen", "виникати"},
            {"beget", "begat  begot", "begotten", "породити"},
            {"breed", "bred", "bred", "розводити(тварин)"},
            {"broadcast", "broadcast", "broadcast", "транслювати"},
            {"burst", "burst", "burst", "лопнути"},
            {"cling", "clung", "clung", "чіплятися"},
            {"can", "could", "could", "можу"},
            {"creep", "crept", "crept", "повзти"},
            {"forbid", "forbade", "forbidden", "забороняти"},
            {"grind", "ground", "ground", "подрібнювати"},
            {"kneel", "knelt", "knelt", "схилити коліна"},
            {"bleed", "bled", "bled", "кровоточити"},
            {"light", "lit lighted", "lit lighted", "засвітити"},
            {"may", "might", "might", "могти з дозволу"},
            {"mow", "mowed", "mown mowed", "косити"},
            {"must", "had to", " had to", "мусити"},
            {"overtake", "overtook", "overtaken", "обганяти"},
            {"saw", "sawed", "sawn sawed", "пиляти"},
            {"shrink", "shrank", "shrunk", "скорочувати"},
            {"sink", "sank", "sunk", "тонути"},
            {"sleep", "slept", "slept", "спати"},
            {"slide", "slid", "slid", "ковзати"},
            {"sow", "sowed", "sown sowed", "садити в грунт"},
            {"spill", "spilt spilled", "spilt spilled", "пролити"},
            {"spit", "spat", "spat", "виплюнути"},
            {"spread", "spread", "spread", "поширювати"},
            {"steal", "stole", "stolen", "красти"},
            {"sting", "stung", "stung", "жалити"},
            {"stink", "stank", "stunk", "смердіти"},
            {"strike", "struck", "struck", "вдарити"},
            {"sweep", "swept", "swept", "підмітати"},
            {"swell", "swelled", "swollen swelled", "набрякати"},
            {"tear", "tore", "torn", "рвати папір"},
            {"throw", "threw", "thrown", "викидати"},
            {"weep", "wept", "wept", "плакати"},
            {"will", "would", "would", "хотіти"},
            {"wind", "wound", "wound", "накручувати"},
            {"ride", "rode", "ridden", "їздити"},
            {"hurt", "hurt", "hurt", "кривдити"},
            {"spell", "spelt spelled", "spelt spelled", "писати по літерах"},
            {"hang", "hung", "hung", "вішати"},
            {"sew", "sewed", "sewn sewed", "шити"},
            {"shall", "should", "should ", "повинний"},
            {"bind", "bound", "bound", "зв'язати"},
            {"lend", "lent", "lent", "позичати"},
            {"dwell", "dwelt", "dwelt dwelled", "оселитися"},
            {"fling", "flung", "flung", "метати"},
            {"partake", "partook", "partaken", "причащатися"}
    };

    public static String[][] getWords1() {
        return WORDS1;
    }

    public static String[][] getWords2() {
        return WORDS2;
    }

    public static String[][] getWords3() {
        return WORDS3;
    }
}


